---

- name: Install dependencies
  apt: name={{item}}
       state=latest
  with_item:
  - unzip
  - python3
  - python3-pip

- name: Download and unarchive Gandyn
  unarchive: src=https://github.com/Chralu/gandyn/archive/master.zip
             dest=/tmp
             remote_src=yes

- name: Install Gandyn
  shell: python3 setup.py install
  args:
    chdir: /tmp/gandyn-master/src

- name: Mkdir /etc/gandyn
  file: name=/etc/gandyn
        state=directory

- name: Make Gandyn executable
  file: path=/usr/local/bin/gandyn.py
        mode='u+x,o+x,g+x'

- name: Copy config file
  template: src=gandyn.conf.j2
            dest=/etc/gandyn/gandyn.conf

- name: Setup cron job
  cron: name='gandyn'
        minute='5'
        job='/usr/local/bin/gandyn.py --config /etc/gandyn/gandyn.conf'
        